spring.application.name=spring-ai-starter


#spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY}
#spring.ai.anthropic.chat.model=claude-3-5-haiku-20241022
#spring.ai.anthropic.chat.enabled=false

spring.ai.ollama.chat.model=llama3.2
spring.ai.ollama.embedding.options.model=nomic-embed-text
spring.ai.ollama.base-url=http://localhost:11434