spring.application.name=spring-ai-starter


spring.ai.anthropic.api-key=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
spring.ai.anthropic.chat.model=claude-3-5-haiku-20241022
