spring.application.name=spring-ai-starter


spring.ai.anthropic.api-key=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
spring.ai.anthropic.chat.model=claude-3-5-haiku-20241022
